default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-ch1v6il269v61fash2i0-a.oregon-postgres.render.com
  username: portyfoliodb_user
  password: 8N3tuMIJkCv9TKpEMwgbkOIRPnJ0NjCj
  database: portyfoliodb
  port: 5432
  sslmode: require

development:
  <<: *default

test:
  <<: *default
  database: portyfoliodb_test

production:
  <<: *default
